### ISSUE TITLE
api stage is "stage" not "prod"

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/live-to-vod-workflow-using-aws-serverless-platform#1]
stage name is not the same in the documentation
In SAM : https://github.com/aws-samples/live-to-vod-workflow-using-aws-serverless-platform/blob/master/sam.yml#L163

In Readme : https://github.com/aws-samples/live-to-vod-workflow-using-aws-serverless-platform/blame/master/README.md#L79

**Comment by markusz** [comment]
Thank you for raising this. I'll look into this

**Comment by markusz** [comment]
I fixed this issue and am closing this issue. 

Thank you again for bringing this to our attention
