### ISSUE TITLE
no attribute 'create_asset'

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/live-to-vod-workflow-using-aws-serverless-platform#3]
```
[ERROR] AttributeError: 'MediaPackage' object has no attribute 'create_asset'
Traceback (most recent call last):
  File "/var/task/handler.py", line 58, in process_harvested_clip
    asset = mediapackage.create_asset(
  File "/var/runtime/botocore/client.py", line 566, in __getattr__
    self.__class__.__name__, item)
```
The code line is here : https://github.com/aws-samples/live-to-vod-workflow-using-aws-serverless-platform/blob/master/handler.py#L58

Perhaps it would be mediapackagevod : https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/mediapackage-vod.html#MediaPackageVod.Client.create_asset

**Comment by markusz** [comment]
Thank you for raising this. I'll look into this

**Comment by markusz** [comment]
I fixed this issue and am closing this issue. 

Thank you again for bringing this to our attention
